console.log('Hello Winc Academy');
let name = 'Mark';
console.log(name);
//    let if = 'not working';
let a = 1;
let b = 2;
console.log(a + b);
let firstName = 'Ellen';
let lastName = ' Degeneres';
console.log(firstName + lastName);
let e = 5;
let f = 2.2;
console.log(e + f);
console.log(e - f);
console.log(e * f);
console.log(e / f);
console.log(e % f);
let age = 45;
console.log(typeof age);
let ageString = 'vijfenveertig';
console.log(typeof ageString);
